version: '3.4'

services:
  myapi:
    image: ${DOCKER_REGISTRY-}myapi
    build:
      context: .
      dockerfile: myAPI/Dockerfile
    environment:
      - CONNECTION_STRING=Server=db;Port=5432;Database=mydatabase;User Id=postgres;Password=password;
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
     - 5432:5432

volumes:
  db-data:
